import { buildRadialLayout } from '../layout/radialLayout'
import { inferExpressionDependencies } from './expressionAnalysis'
import type { DerivationNode, EmlGraph, Family, GraphEdge } from './types'
import {
  binary,
  constExpr,
  num,
  unary,
  varExpr,
  type ClassicalExpr,
} from './expression'
import { compileExpressionToEml } from './compiler'

const x = varExpr('x')
const y = varExpr('y')

function withAliases(extra: string[] = []): string[] {
  const compact = extra.map((value) => value.replaceAll(' ', ''))
  return Array.from(new Set([...extra, ...compact]))
}

function autoTree(
  formula: ClassicalExpr,
  options: { witnessForOne?: boolean; witnessForIdentity?: boolean } = {},
) {
  return compileExpressionToEml(formula, {
    preferWitnessForOne: options.witnessForOne,
    preferWitnessForIdentity: options.witnessForIdentity,
  })
}

const DERIVATION_CHAIN: DerivationNode[] = [
  {
    id: 'one',
    name: '1',
    latex: '1',
    family: 'primitive',
    depth: 0,
    isLandmark: true,
    description: 'The primitive constant paired with the EML operator.',
    dependencies: [],
    aliases: ['1', 'one'],
    formula: num(1),
    emlTree: autoTree(num(1), { witnessForOne: true }),
  },
  {
    id: 'x_anchor',
    name: 'x',
    latex: 'x',
    family: 'primitive',
    depth: 0,
    isLandmark: true,
    description: 'Independent variable anchor used by variable-dependent EML subtrees.',
    dependencies: [],
    aliases: ['x', 'identity'],
    formula: varExpr('x'),
    emlTree: autoTree(varExpr('x'), { witnessForIdentity: true }),
  },
  {
    id: 'e',
    name: 'e',
    latex: 'e',
    family: 'core',
    depth: 1,
    isLandmark: true,
    description: 'Euler’s number, reconstructed directly as eml(1, 1).',
    dependencies: ['one'],
    aliases: ['e', 'eml(1,1)'],
    formula: constExpr('e'),
    emlTree: autoTree(constExpr('e')),
  },
  {
    id: 'exp',
    name: 'exp(x)',
    latex: 'e^x',
    family: 'core',
    depth: 1,
    isLandmark: true,
    description: 'Exact exponential witness: exp(x) = eml(x, 1).',
    dependencies: ['one'],
    aliases: ['exp(x)', 'e^x', 'expx'],
    formula: unary('exp', x),
    emlTree: autoTree(unary('exp', x)),
  },
  {
    id: 'ln',
    name: 'ln(x)',
    latex: '\\ln x',
    family: 'core',
    depth: 2,
    isLandmark: true,
    description: 'The first non-trivial reconstruction in the chain.',
    dependencies: ['one', 'exp'],
    aliases: ['ln(x)', 'log(x)', 'lnx'],
    formula: unary('ln', x),
    emlTree: autoTree(unary('ln', x)),
  },
  {
    id: 'zero',
    name: '0',
    latex: '0',
    family: 'arithmetic',
    depth: 3,
    isLandmark: true,
    description: 'Zero emerges as ln(1) inside the compiled chain.',
    dependencies: ['ln', 'one'],
    aliases: ['0', 'zero'],
    formula: num(0),
    emlTree: autoTree(num(0)),
  },
  {
    id: 'sub',
    name: 'x - y',
    latex: 'x - y',
    family: 'arithmetic',
    depth: 3,
    isLandmark: false,
    description: 'Direct witness from the supplement: x − y = eml(ln(x), exp(y)).',
    dependencies: ['exp', 'ln'],
    aliases: ['x-y', 'subtract', 'subtraction'],
    formula: binary('sub', x, y),
    emlTree: autoTree(binary('sub', x, y)),
  },
  {
    id: 'neg',
    name: '-x',
    latex: '-x',
    family: 'arithmetic',
    depth: 3,
    isLandmark: false,
    description: 'Negation is built by subtracting x from zero.',
    dependencies: ['sub', 'zero'],
    aliases: ['-x', 'neg(x)', 'negation'],
    formula: unary('neg', x),
    emlTree: autoTree(unary('neg', x)),
  },
  {
    id: 'neg_one',
    name: '-1',
    latex: '-1',
    family: 'arithmetic',
    depth: 4,
    isLandmark: true,
    description: 'Negative unity reconstructed from 0 − 1.',
    dependencies: ['neg', 'one'],
    aliases: ['-1', 'negative one'],
    formula: num(-1),
    emlTree: autoTree(num(-1)),
  },
  {
    id: 'add',
    name: 'x + y',
    latex: 'x + y',
    family: 'arithmetic',
    depth: 4,
    isLandmark: false,
    description: 'Addition is assembled by x − (−y).',
    dependencies: ['sub', 'neg'],
    aliases: ['x+y', 'addition', 'plus'],
    formula: binary('add', x, y),
    emlTree: autoTree(binary('add', x, y)),
  },
  {
    id: 'inv',
    name: '1/x',
    latex: '\\frac{1}{x}',
    family: 'arithmetic',
    depth: 4,
    isLandmark: false,
    description: 'Reciprocal via exp(−ln(x)).',
    dependencies: ['exp', 'ln', 'neg'],
    aliases: ['1/x', 'inverse', 'reciprocal'],
    formula: binary('div', num(1), x),
    emlTree: autoTree(binary('div', num(1), x)),
  },
  {
    id: 'two',
    name: '2',
    latex: '2',
    family: 'constants',
    depth: 5,
    isLandmark: true,
    description: 'Two reconstructed from 1 − (−1).',
    dependencies: ['add', 'one'],
    aliases: ['2', 'two'],
    formula: num(2),
    emlTree: autoTree(num(2)),
  },
  {
    id: 'mul',
    name: 'x * y',
    latex: 'x \\cdot y',
    family: 'arithmetic',
    depth: 5,
    isLandmark: false,
    description: 'Multiplication from exp(ln(x) + ln(y)).',
    dependencies: ['exp', 'ln', 'add'],
    aliases: ['x*y', 'x·y', 'multiply', 'multiplication'],
    formula: binary('mul', x, y),
    emlTree: autoTree(binary('mul', x, y)),
  },
  {
    id: 'div',
    name: 'x / y',
    latex: '\\frac{x}{y}',
    family: 'arithmetic',
    depth: 5,
    isLandmark: false,
    description: 'Division using multiplication and reciprocal.',
    dependencies: ['mul', 'inv'],
    aliases: ['x/y', 'divide', 'division'],
    formula: binary('div', x, y),
    emlTree: autoTree(binary('div', x, y)),
  },
  {
    id: 'sq',
    name: 'x^2',
    latex: 'x^2',
    family: 'power',
    depth: 5,
    isLandmark: false,
    description: 'Squaring comes from x times itself.',
    dependencies: ['mul'],
    aliases: ['x^2', 'square', 'sqr(x)', 'x²'],
    formula: binary('pow', x, num(2)),
    emlTree: autoTree(binary('pow', x, num(2))),
  },
  {
    id: 'imag',
    name: 'i',
    latex: 'i',
    family: 'constants',
    depth: 6,
    isLandmark: true,
    description: 'Imaginary unit obtained from the branch structure of ln(−1).',
    dependencies: ['ln', 'neg_one', 'pi'],
    aliases: ['i', 'imaginary unit'],
    formula: constExpr('i'),
    emlTree: null,
  },
  {
    id: 'pow',
    name: 'x^y',
    latex: 'x^y',
    family: 'power',
    depth: 6,
    isLandmark: false,
    description: 'Exponentiation compiled as exp(y · ln(x)).',
    dependencies: ['exp', 'ln', 'mul'],
    aliases: withAliases(['x^y', 'pow(x,y)', 'xy power', 'xʸ']),
    formula: binary('pow', x, y),
    emlTree: autoTree(binary('pow', x, y)),
  },
  {
    id: 'sqrt',
    name: 'sqrt(x)',
    latex: '\\sqrt{x}',
    family: 'power',
    depth: 6,
    isLandmark: false,
    description: 'Square root from exp(ln(x) / 2).',
    dependencies: ['pow', 'two'],
    aliases: ['sqrt(x)', '√x', 'root'],
    formula: unary('sqrt', x),
    emlTree: autoTree(unary('sqrt', x)),
  },
  {
    id: 'pi',
    name: 'pi',
    latex: '\\pi',
    family: 'constants',
    depth: 6,
    isLandmark: true,
    description: 'Pi recovered through the principal branch of ln(−1).',
    dependencies: ['ln', 'neg_one', 'pow', 'sqrt', 'neg'],
    aliases: ['pi', 'π'],
    formula: constExpr('pi'),
    emlTree: null,
  },
  {
    id: 'sigma',
    name: 'sigma(x)',
    latex: '\\sigma(x)',
    family: 'hyperbolic',
    depth: 6,
    isLandmark: false,
    description: 'Logistic sigmoid from 1 / (1 + e^(−x)).',
    dependencies: ['inv', 'add', 'one', 'exp', 'neg'],
    aliases: ['sigma(x)', 'sigmoid', 'logistic'],
    formula: binary('div', num(1), binary('add', num(1), unary('exp', unary('neg', x)))),
    emlTree: null,
  },
  {
    id: 'cosh',
    name: 'cosh(x)',
    latex: '\\cosh x',
    family: 'hyperbolic',
    depth: 7,
    isLandmark: false,
    description: 'Hyperbolic cosine from (e^x + e^(−x)) / 2.',
    dependencies: ['exp', 'neg', 'add', 'div', 'two'],
    aliases: ['cosh(x)', 'hyperbolic cosine'],
    formula: unary('cosh', x),
    emlTree: null,
  },
  {
    id: 'sinh',
    name: 'sinh(x)',
    latex: '\\sinh x',
    family: 'hyperbolic',
    depth: 7,
    isLandmark: false,
    description: 'Hyperbolic sine from (e^x − e^(−x)) / 2.',
    dependencies: ['exp', 'neg', 'sub', 'div', 'two'],
    aliases: ['sinh(x)', 'hyperbolic sine'],
    formula: unary('sinh', x),
    emlTree: null,
  },
  {
    id: 'tanh',
    name: 'tanh(x)',
    latex: '\\tanh x',
    family: 'hyperbolic',
    depth: 7,
    isLandmark: false,
    description: 'Hyperbolic tangent as sinh(x) / cosh(x).',
    dependencies: ['sinh', 'cosh', 'div'],
    aliases: ['tanh(x)', 'hyperbolic tangent'],
    formula: unary('tanh', x),
    emlTree: null,
  },
  {
    id: 'cos',
    name: 'cos(x)',
    latex: '\\cos x',
    family: 'trigonometric',
    depth: 8,
    isLandmark: true,
    description: 'Circular cosine compiled through the complex hyperbolic identity.',
    dependencies: ['cosh', 'imag', 'mul', 'neg'],
    aliases: ['cos(x)', 'cosine'],
    formula: unary('cos', x),
    emlTree: null,
  },
  {
    id: 'sin',
    name: 'sin(x)',
    latex: '\\sin x',
    family: 'trigonometric',
    depth: 8,
    isLandmark: true,
    description: 'Circular sine recovered from a cosine phase shift.',
    dependencies: ['cos', 'pi', 'two', 'sub', 'div'],
    aliases: ['sin(x)', 'sine'],
    formula: unary('sin', x),
    emlTree: null,
  },
  {
    id: 'tan',
    name: 'tan(x)',
    latex: '\\tan x',
    family: 'trigonometric',
    depth: 8,
    isLandmark: false,
    description: 'Tangent as sin(x) / cos(x).',
    dependencies: ['sin', 'cos', 'div'],
    aliases: ['tan(x)', 'tangent'],
    formula: unary('tan', x),
    emlTree: null,
  },
  {
    id: 'arsinh',
    name: 'arsinh(x)',
    latex: '\\operatorname{arsinh} x',
    family: 'hyperbolic',
    depth: 8,
    isLandmark: false,
    description: 'Inverse hyperbolic sine through a logarithmic square-root form.',
    dependencies: ['ln', 'sqrt', 'add', 'sq', 'one'],
    aliases: ['arsinh(x)', 'asinh(x)'],
    formula: unary('arsinh', x),
    emlTree: null,
  },
  {
    id: 'arcosh',
    name: 'arcosh(x)',
    latex: '\\operatorname{arcosh} x',
    family: 'hyperbolic',
    depth: 8,
    isLandmark: false,
    description: 'Inverse hyperbolic cosine through its principal-branch logarithm.',
    dependencies: ['ln', 'sqrt', 'mul', 'sub', 'add', 'one'],
    aliases: ['arcosh(x)', 'acosh(x)'],
    formula: unary('arcosh', x),
    emlTree: null,
  },
  {
    id: 'artanh',
    name: 'artanh(x)',
    latex: '\\operatorname{artanh} x',
    family: 'hyperbolic',
    depth: 8,
    isLandmark: false,
    description: 'Inverse hyperbolic tangent through a logarithmic quotient.',
    dependencies: ['ln', 'add', 'sub', 'div', 'one', 'two'],
    aliases: ['artanh(x)', 'atanh(x)'],
    formula: unary('artanh', x),
    emlTree: null,
  },
  {
    id: 'arcsin',
    name: 'arcsin(x)',
    latex: '\\arcsin x',
    family: 'trigonometric',
    depth: 8,
    isLandmark: false,
    description: 'Inverse sine from the principal logarithmic form.',
    dependencies: ['ln', 'imag', 'sqrt', 'sq', 'sub', 'mul'],
    aliases: ['arcsin(x)', 'asin(x)'],
    formula: unary('arcsin', x),
    emlTree: null,
  },
  {
    id: 'arccos',
    name: 'arccos(x)',
    latex: '\\arccos x',
    family: 'trigonometric',
    depth: 8,
    isLandmark: false,
    description: 'Inverse cosine via π/2 − arcsin(x).',
    dependencies: ['pi', 'two', 'arcsin', 'sub', 'div'],
    aliases: ['arccos(x)', 'acos(x)'],
    formula: unary('arccos', x),
    emlTree: null,
  },
  {
    id: 'arctan',
    name: 'arctan(x)',
    latex: '\\arctan x',
    family: 'trigonometric',
    depth: 8,
    isLandmark: false,
    description: 'Inverse tangent via the principal complex logarithm.',
    dependencies: ['ln', 'imag', 'sub', 'add', 'mul', 'div'],
    aliases: ['arctan(x)', 'atan(x)'],
    formula: unary('arctan', x),
    emlTree: null,
  },
]

interface GenerateOptions {
  depth: number
  families: Family[]
}

export function generateEmlGraph(options: GenerateOptions): EmlGraph {
  const enabledFamilies = new Set<Family>(['primitive', ...options.families])
  const visible = DERIVATION_CHAIN.filter(
    (node) => node.depth <= options.depth && enabledFamilies.has(node.family),
  ).map((node) => ({
    ...node,
    dependencies:
      node.id === 'one' || node.id === 'x_anchor' || !node.formula
        ? []
        : inferExpressionDependencies(node.formula),
  }))
  const visibleIds = new Set(visible.map((node) => node.id))

  const edges: GraphEdge[] = []
  for (const node of visible) {
    for (const dep of node.dependencies) {
      if (visibleIds.has(dep)) {
        edges.push({ id: `e-${dep}-${node.id}`, from: dep, to: node.id })
      }
    }
  }

  return {
    nodes: buildRadialLayout(visible, edges),
    edges,
    rootId: 'one',
  }
}
